<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
   'Account information will be sent to your email' => 'Tilitiedot lähetetään sähköpostiisi',
  'Please select another one' => 'Ole hyvä ja valitse toinen',
  'The company email. You will receive the account information here.' => 'Yrityksen sähköpostiosoite. Tilin tiedot lähetetään tänne.',
  'The company name. Be creative and stand out!' => 'Yrityksen nimi. Ole luova ja erotu joukosta!',
  'This company name is already taken.' => 'Tämä yrityksen nimi on jo käytössä.',
  'Communication' => 'Yhteydet',
  'Company' => 'Yritys',
  'Description' => 'Kuvaus',
  'Expenses' => 'Materiaalikulut',
  'Health' => 'Terveys',
  'Loans' => 'Lainat',
  'Other' => 'Muut',
  'OtherExpenses' => 'Muut kulut',
  'Password' => 'Salasana',
  'Rents' => 'Vuokrat',
  'Salaries' => 'Palkat',
  'SideExpenses' => 'Sivukulut',
  'Turnover' => 'Liikevaihto',
  'UserId' => 'Käyttäjätunnus',
  'Verify' => 'Tarkista',
  'What should you do next?' => 'Mitä kannattaa tehdä seuraavaksi?',
  'computer-assembly' => 'Tietokoneiden kokoonpano',
  'computer-retail' => 'Tietokoneiden jälleenmyynti',
  'Active' => 'Aktiivinen',
  'Business ID' => 'Y-tunnus',
  'Cost-benefit calculation' => 'Liiketoimintalaskelma',
  'Create' => 'Perusta',
  'Create Time' => 'Luontiaika',
  'Create a company' => 'Perusta yritys',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ID' => 'ID',
  'Industry' => 'Toimiala',
  'Info' => 'Tiedot',
  'Monthly' => 'Kuukaudessa',
  'Name' => 'Nimi',
  'Company name' => 'Yrityksen nimi',
  'Please provide a token key' => 'Ole hyvä ja anna perustamisavain',
  'Profit' => 'Tuotto',
  'Select industry' => 'Valitse toimiala',
  'Tag' => 'Tunnus',
  'The ERP system' => 'ERP-järjestelmä',
  'The bank' => 'Pankki',
  'The learning environment' => 'Oppimisympäristö',
  'Token key' => 'Perustamisavain',
  'Validate' => 'Tarkista',
  'Welcome' => 'Tervetuloa',
  'Yearly' => 'Vuodessa',
  'Your company has been created!' => 'Yrityksesi on luotu!',
);
