<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'BankAccount' => '@@Pankkitunnukset@@',
  'BusinessId' => '@@Y-tunnus@@',
  'Communication' => '@@Yhteydet@@',
  'CostBenefitCalculation' => '@@Liiketoimintasuunnitelma@@',
  'CreateCompany' => '@@Luo yritys@@',
  'CreatingACompany' => '@@Luodaan yritystä...@@',
  'Description' => '@@Kuvaus@@',
  'EachTokenKeyCanBeUsedOnlyOnce' => '@@Jokaisen  perustamisavaimen voi käyttää vain kerran@@',
  'EmailIsInvalid' => '@@Sähköpostiosoite on virheellinen@@',
  'ErrorWhileDecidingFormStep' => '@@Virheellinen lomakkeen vaihe@@',
  'Expenses' => '@@Materiaalikulut@@',
  'FuturalityAccount' => '@@Futurality-tilisi@@',
  'FuturalityLearningEnvironment' => '@@Futurality-oppimisympäristöön@@',
  'GrabACupOfCoffee' => '@@Tässä on hyvä väli hakea kuppi kahvia.@@',
  'HaveFun' => '@@Pidä hauskaa!@@',
  'Health' => '@@Terveys@@',
  'Loans' => '@@Lainat@@',
  'LoginFrom' => '@@Kirjautuminen@@',
  'OpenERPAccount' => '@@OpenERP-tunnukset@@',
  'Other' => '@@Muut@@',
  'OtherExpenses' => '@@Muut kulut@@',
  'Password' => '@@Salasana@@',
  'PleaseBePatient' => '@@Ole hyvä ja odota kärsivällisesti!@@',
  'PleaseGiveATokenKey' => '@@Ole hyvä, ja anna perustamisavain@@',
  'Profit' => '@@Tuotto@@',
  'Rents' => '@@Vuokrat@@',
  'Salaries' => '@@Palkat@@',
  'SelectIndustry' => '@@Valitse toimiala@@',
  'SideExpenses' => '@@Sivukulut@@',
  'TheBank' => '@@Pankki@@',
  'TheERPSystem' => '@@ERP-järjestelmä@@',
  'TheLearningEnvironment' => '@@Oppimisympäristö@@',
  'TokenKey' => '@@Perustamisavain@@',
  'ToolTipCommunication' => '@@Yrityksen yhteydet ulkomaailmaan. Sisältää puhelimet, internetin, yms. Ei sisällä markkinointikuluja@@',
  'ToolTipExpenses' => '@@Hankkimiskustannukset. Tämä sisältää esim. lopputuotteen kokoonpanoa varten ostettavat osat.@@',
  'ToolTipHealth' => '@@Työntekijöiden terveyteen suunnatut kulut.@@',
  'ToolTipLoans' => '@@Lainanhoitokulut. Sisältää koron, maksuerän ja mahdolliset palvelu- tai hoitomaksut.@@',
  'ToolTipOther' => '@@Kulut, jotka eivät sovi muihin kenttiin.@@',
  'ToolTipProfit' => '@@Yrityksen tulos, joka jää kaikkien kulujen jälkeen. Tämän olisi syytä olla positiivinen, mikäli yritys aikoo pysyä toiminnassa.@@',
  'ToolTipRents' => '@@Vuokrakulut yhteensä. Tämä sisältää toimitilan vuokran, ja mahdollisten varastotilojen vuokran.@@',
  'ToolTipSalaries' => '@@Palkkakulut ilman sivukuluja. Tämä on usein yksi yrityksen suurimmista kiinteistä menoeristä.@@',
  'ToolTipSideExpenses' => '@@Eläke-, sairaus-, työttömyys-, tapaturma-, ja muut pakolliset vakuutusmaksut.@@',
  'ToolTipTurnover' => '@@Myyntituotot, eli yritykselle tuleva raha. Ei sisällä lainoja.@@',
  'TooltipCompanyName' => '@@Yrityksen nimi. Erotu joukosta - ole luova!@@',
  'TooltipEmail' => '@@Yrityksen sähköpostiosoite. Saat tilisi tiedot tähän sähköpostiin.@@',
  'TooltipEmployees' => '@@Yrityksen työntekijöiden määrä.@@',
  'TooltipIndustry' => '@@Yrityksen päätoimiala. Tämän perusteella annetaan ohjearvoja liiketoimintalaskelmaa varten.@@',
  'Turnover' => '@@Liikevaihto@@',
  'UserId' => '@@Käyttäjätunnus@@',
  'Verify' => '@@Tarkista@@',
  'WelcomeToFuturality' => '@@Tervetuloa Futuralityyn!@@',
  'WhatIsNext' => '@@Mitä seuraavaksi?@@',
  'YouHaveCreatedACompanyInThe' => '@@Olet luonut yrityksen@@',
  'YourBusinessIdIs' => '@@Y-tunnuksesi on@@',
  'YourCompanyNameIs' => '@@Yrityksesi nimi on@@',
  'YourCompanyTagIs' => '@@Yrityksesi tunnus on@@',
  'computer-assembly' => '@@Tietokoneiden kokoonpano@@',
  'computer-retail' => '@@Tietokoneiden jälleenmyynti@@',
  'Active' => 'Aktiivinen',
  'Business ID' => 'Y-tunnus',
  'Create' => 'Luo',
  'Create Time' => 'Luontiaika',
  'Create a company' => 'Perusta yritys',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ID' => 'ID',
  'Industry' => 'Toimiala',
  'Monthly' => 'Kuukaudessa',
  'Name' => 'Nimi',
  'Please provide a token key' => 'Ole hyvä ja anna perustamisavain',
  'Tag' => 'Tunnus',
  'Token key' => 'Perustamisavain',
  'Validate' => 'Tarkista',
  'Welcome' => 'Tervetuloa',
  'Yearly' => 'Vuodessa',
);
