<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'BankAccount' => '@@Pankkitunnukset@@',
  'Communication' => 'Yhteydet',
  'Company' => 'Yritys',
  'CostBenefitCalculation' => 'Liiketoimintalaskelma',
  'CreateCompany' => '@@Luo yritys@@',
  'CreatingACompany' => '@@Luodaan yritystä...@@',
  'Description' => 'Kuvaus',
  'EachTokenKeyCanBeUsedOnlyOnce' => '@@Jokaisen  perustamisavaimen voi käyttää vain kerran@@',
  'EmailIsInvalid' => '@@Sähköpostiosoite on virheellinen@@',
  'ErrorWhileDecidingFormStep' => '@@Virheellinen lomakkeen vaihe@@',
  'Expenses' => 'Materiaalikulut',
  'FuturalityAccount' => '@@Futurality-tilisi@@',
  'FuturalityLearningEnvironment' => '@@Futurality-oppimisympäristöön@@',
  'GrabACupOfCoffee' => '@@Tässä on hyvä väli hakea kuppi kahvia.@@',
  'HaveFun' => '@@Pidä hauskaa!@@',
  'Health' => 'Terveys',
  'Loans' => 'Lainat',
  'LoginFrom' => '@@Kirjautuminen@@',
  'OpenERPAccount' => '@@OpenERP-tunnukset@@',
  'Other' => 'Muut',
  'OtherExpenses' => 'Muut kulut',
  'Password' => '@@Salasana@@',
  'PleaseBePatient' => '@@Ole hyvä ja odota kärsivällisesti!@@',
  'PleaseGiveATokenKey' => '@@Ole hyvä, ja anna perustamisavain@@',
  'Rents' => 'Vuokrat',
  'Salaries' => 'Palkat',
  'SideExpenses' => 'Sivukulut',
  'The bank' => 'Pankki',
  'The ERP system' => 'ERP-järjestelmä',
  'The learning environment' => 'Oppimisympäristö',
  'Turnover' => 'Liikevaihto',
  'UserId' => '@@Käyttäjätunnus@@',
  'Verify' => 'Tarkista',
  'WelcomeToFuturality' => '@@Tervetuloa Futuralityyn!@@',
  'YouHaveCreatedACompanyInThe' => '@@Olet luonut yrityksen@@',
  'YourBusinessIdIs' => '@@Y-tunnuksesi on@@',
  'YourCompanyNameIs' => '@@Yrityksesi nimi on@@',
  'YourCompanyTagIs' => '@@Yrityksesi tunnus on@@',
  'computer-assembly' => 'Tietokoneiden kokoonpano',
  'computer-retail' => 'Tietokoneiden jälleenmyynti',
  'Active' => 'Aktiivinen',
  'Business ID' => 'Y-tunnus',
  'Cost-benefit calculation' => 'Liiketoimintalaskelma',
  'Create' => 'Perusta',
  'Create Time' => 'Luontiaika',
  'Create a company' => 'Perusta yritys',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ID' => 'ID',
  'Industry' => 'Toimiala',
  'Info' => 'Tiedot',
  'Monthly' => 'Kuukaudessa',
  'Name' => 'Nimi',
  'Please provide a token key' => 'Ole hyvä ja anna perustamisavain',
  'Profit' => '@@Tuotto@@',
  'Select industry' => 'Valitse toimiala',
  'Tag' => 'Tunnus',
  'Token key' => 'Perustamisavain',
  'Validate' => 'Tarkista',
  'Welcome' => 'Tervetuloa',
  'Yearly' => 'Vuodessa',
  'What should you do next?' => 'Mitä kannattaa tehdä seuraaksi?',
  'Your company has been created!' => 'Yrityksesi on luotu!'
);
