<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  		'Value' => 'Arvo',
		'Monthly value' => 'Kuukausittainen arvo',
		'Yearly value' => 'Vuosittainen arvo',
		'turnover' => 'liikevaihto',
		'salaries' => 'palkat',
		'expenses' => 'materiaalikulut',
		'loans' => 'lainat',
		'rents' => 'vuokrat',
		'communication' => 'yhteydet',
		'health' => 'terveys',
		'sideExpenses' => 'sivukulut',
		'otherExpenses' => 'muut kulut',
		'profit' => 'tuotto',
		'TooltipCommunication' => 'Yrityksen yhteydet ulkomaailmaan. Sisältää puhelimet, internetin, yms. Ei sisällä markkinointikuluja',
		'TooltipExpenses' => 'Hankkimiskustannukset. Tämä sisältää esim. lopputuotteen kokoonpanoa varten ostettavat osat.',
		'TooltipHealth' => 'Työntekijöiden terveyteen suunnatut kulut.',
		'TooltipLoans' => 'Lainanhoitokulut. Sisältää koron, maksuerän ja mahdolliset palvelu- tai hoitomaksut.',
		'TooltipOtherExpenses' => 'Kulut, jotka eivät sovi muihin kenttiin.',
		'TooltipProfit' => 'Yrityksen tulos, joka jää kaikkien kulujen jälkeen. Tämän olisi syytä olla positiivinen, mikäli yritys aikoo pysyä toiminnassa.',
		'TooltipRents' => 'Vuokrakulut yhteensä. Tämä sisältää toimitilan vuokran, ja mahdollisten varastotilojen vuokran.',
		'TooltipSalaries' => 'Palkkakulut ilman sivukuluja. Tämä on usein yksi yrityksen suurimmista kiinteistä menoeristä.',
		'TooltipSideExpenses' => 'Eläke-, sairaus-, työttömyys-, tapaturma-, ja muut pakolliset vakuutusmaksut.',
		'TooltipTurnover' => 'Myyntituotot, eli yritykselle tuleva raha. Ei sisällä lainoja.',
		'TooltipCompanyName' => 'Yrityksen nimi. Erotu joukosta - ole luova!',
		'TooltipEmail' => 'Yrityksen sähköpostiosoite. Saat tilisi tiedot tähän sähköpostiin.',
		'TooltipEmployees' => 'Yrityksen työntekijöiden määrä.',
		'TooltipIndustry' => 'Yrityksen päätoimiala. Tämän perusteella annetaan ohjearvoja liiketoimintalaskelmaa varten.',
);
