<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Monthly communication value' => 'Kuukausittaiset yhteyskulut',
  'Monthly expenses value' => 'Kuukausittaiset materiaalikulut',
  'Monthly health value' => 'Kuukausittaiset terveyskulut',
  'Monthly loans value' => 'Kuukausittaiset lainakulut',
  'Monthly other expenses value' => 'Kuukausittaiset muut kulut',
  'Monthly profit' => 'Kuukausittainen tuotto',
  'Monthly rents value' => 'Kuukausittaiset vuokrakulut',
  'Monthly salaries value' => 'Kuukausittaiset palkkakulut',
  'Monthly side expenses value' => 'Kuukausittaiset sivukulut',
  'Monthly turnover value' => 'Kuukausittainen liikevaihto',
  'Yearly communication value' => 'Vuosittaiset yhteyskulut',
  'Yearly expenses value' => 'Vuosittaiset materiaalikulut',
  'Yearly health value' => 'Vuosittaiset terveyskulut',
  'Yearly loans value' => 'Vuosittaiset lainakulut',
  'Yearly other expenses value' => 'Vuosittaiset muut kulut',
  'Yearly profit' => 'Vuosittainen tuotto',
  'Yearly rents value' => 'Vuosittaiset lainakulut',
  'Yearly salaries value' => 'Vuosittaiset palkkakulut',
  'Yearly side expenses value' => 'Vuosittaiset sivukulut',
  'Yearly turnover value' => 'Vuosittainen liikevaihto',
  'Monthly value' => 'Kuukausittainen arvo',
  'TooltipCommunication' => 'Yrityksen yhteydet ulkomaailmaan. Sisältää puhelimet, internetin, yms. Ei sisällä markkinointikuluja',
  'TooltipCompanyName' => 'Yrityksen nimi. Erotu joukosta - ole luova!',
  'TooltipEmail' => 'Yrityksen sähköpostiosoite. Saat tilisi tiedot tähän sähköpostiin.',
  'TooltipEmployees' => 'Yrityksen työntekijöiden määrä.',
  'TooltipExpenses' => 'Hankkimiskustannukset. Tämä sisältää esim. lopputuotteen kokoonpanoa varten ostettavat osat.',
  'TooltipHealth' => 'Työntekijöiden terveyteen suunnatut kulut.',
  'TooltipIndustry' => 'Yrityksen päätoimiala. Tämän perusteella annetaan ohjearvoja liiketoimintalaskelmaa varten.',
  'TooltipLoans' => 'Lainanhoitokulut. Sisältää koron, maksuerän ja mahdolliset palvelu- tai hoitomaksut.',
  'TooltipOtherExpenses' => 'Kulut, jotka eivät sovi muihin kenttiin.',
  'TooltipProfit' => 'Yrityksen tulos, joka jää kaikkien kulujen jälkeen. Tämän olisi syytä olla positiivinen, mikäli yritys aikoo pysyä toiminnassa.',
  'TooltipRents' => 'Vuokrakulut yhteensä. Tämä sisältää toimitilan vuokran, ja mahdollisten varastotilojen vuokran.',
  'TooltipSalaries' => 'Palkkakulut ilman sivukuluja. Tämä on usein yksi yrityksen suurimmista kiinteistä menoeristä.',
  'TooltipSideExpenses' => 'Eläke-, sairaus-, työttömyys-, tapaturma-, ja muut pakolliset vakuutusmaksut.',
  'TooltipTurnover' => 'Myyntituotot, eli yritykselle tuleva raha. Ei sisällä lainoja.',
  'communication' => 'yhteydet',
  'expenses' => 'materiaalikulut',
  'health' => 'terveys',
  'loans' => 'lainat',
  'otherExpenses' => 'muut kulut',
  'profit' => 'tuotto',
  'rents' => 'vuokrat',
  'salaries' => 'palkat',
  'sideExpenses' => 'sivukulut',
  'turnover' => 'liikevaihto',
  'Value' => 'Arvo',
  'Yearly value' => 'Vuosittainen arvo',
);
