<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Error while saving the company. Please report this incident to helpdesk@futurality.fi' => 'Virhe tallentaessa yritystä. Ole hyvä ja ilmoita asiasta osoitteeseen helpdesk@futurality.fi',
  'Create date' => 'Luontipäivä',
  'Expiration date' => 'Erääntymispäivä',
  'ID' => 'ID',
  'Invalid token key.' => 'Virheellinen perustamisavain',
  'Lifetime' => 'Kesto',
  'Reclaim date' => 'Käyttöönottopäivä',
  'Token customer' => 'Avaimen asiakas',
  'Token key' => 'Perustamisavain',
  'Token key is already used on {dateTime}.' => 'Perustamisavain on käytetty {dateTime}',
  'Token setup' => 'Avaimen asetukset',
);
