<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Please select another one' => '',
  'The company email. You will receive the account information here.' => '',
  'The company name. Be creative and stand out!' => '',
  'This company name is already taken.' => '',
  'Communication' => '',
  'Company' => '',
  'Description' => '',
  'Expenses' => '',
  'Health' => '',
  'Loans' => '',
  'Other' => '',
  'OtherExpenses' => '',
  'Password' => '',
  'Rents' => '',
  'Salaries' => '',
  'SideExpenses' => '',
  'Turnover' => '',
  'UserId' => '',
  'Verify' => '',
  'What should you do next?' => '',
  'computer-assembly' => '',
  'computer-retail' => '',
  'Active' => '',
  'Business ID' => '',
  'Cost-benefit calculation' => '',
  'Create' => '',
  'Create Time' => '',
  'Create a company' => '',
  'Email' => '',
  'Employees' => '',
  'ID' => '',
  'Industry' => '',
  'Info' => '',
  'Monthly' => '',
  'Name' => '',
  'Please provide a token key' => '',
  'Profit' => '',
  'Select industry' => '',
  'Tag' => '',
  'The ERP system' => '',
  'The bank' => '',
  'The learning environment' => '',
  'Token key' => '',
  'Validate' => '',
  'Welcome' => '',
  'Yearly' => '',
  'Your company has been created!' => '',
);
