<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Monthly communication value' => '',
  'Monthly expenses value' => '',
  'Monthly health value' => '',
  'Monthly loans value' => '',
  'Monthly other expenses value' => '',
  'Monthly profit' => '',
  'Monthly rents value' => '',
  'Monthly salaries value' => '',
  'Monthly side expenses value' => '',
  'Monthly turnover value' => '',
  'Yearly communication value' => '',
  'Yearly expenses value' => '',
  'Yearly health value' => '',
  'Yearly loans value' => '',
  'Yearly other expenses value' => '',
  'Yearly profit' => '',
  'Yearly rents value' => '',
  'Yearly salaries value' => '',
  'Yearly side expenses value' => '',
  'Yearly turnover value' => '',
  'Yearly value' => '',
  'Monthly value' => '',
  'Value' => '',
);
